# https://stockmarketmba.com/globalstockexchanges.php

exchanges = {
    'USA': '',
    'Germany': 'XETR',
    'Hong Kong': 'XHKG',
    'Japan': 'XTKS',
    'France': 'XPAR',
    'Canada': 'XTSE',
    'United Kingdom': 'XLON',
    'Switzerland': 'XSWX',
    'Australia': 'XASX',
    'South Korea': 'XKRX',
    'The Netherlands': 'XAMS',
    'Spain': 'XMAD',
    'Russia': 'MISX',
    'Italy': 'XMIL',
    'Belgium': 'XBRU',
    'Mexiko': 'XMEX',
    'Sweden': 'XSTO',
    'Norway': 'XOSL',
    'Finland': 'XHEL',
    'Denmark': 'XCSE',
    'Austria': 'XWBO'
}

exchanges_untested = {
    'Argentina': 'XBUE',
    'Australia_XNEC': 'XNEC',
    'Australia': 'XASX',
    'Austria': 'XWBO',
    'Bahrain': 'XBAH',
    'Bangladesh': 'XDHA',
    'Belgium': 'XBRU',
    'Brazil': 'BVMF',
    'Canada_XCNQ': 'XCNQ',
    'Canada': 'XTSE',
    'Canada_XTSX': 'XTSX',
    'Canada_NEOE': 'NEOE',
    'Chile': 'XSGO',
    'China_SHG': 'XSHG',
    'China': 'XSHE',
    'Colombia': 'XBOG',
    'Croatia': 'XZAG',
    'Cyprus': 'XCYS',
    'Czech Republic': 'XPRA',
    'Denmark': 'XCSE',
    'Egypt': 'XCAI',
    'Finland': 'XHEL',
    'France': 'XPAR',
    'Germany_XEQT': 'XEQT',
    'Germany_XBER': 'XBER',
    'Germany_XDUS': 'XDUS',
    'Germany_XFRA': 'XFRA',
    'Germany_XMUN': 'XMUN',
    'Germany_XSTU': 'XSTU',
    'Germany': 'XETR',
    'Germany_XQTX': 'XQTX',
    'Greece': 'XATH',
    'Hong Kong': 'XHKG',
    'Hungary': 'XBUD',
    'Iceland': 'XICE',
    'India_XBOM': 'XBOM',
    'India': 'XNSE',
    'Indonesia': 'XIDX',
    'Ireland': 'XDUB',
    'Israel': 'XTAE',
    'Italy': 'MTAA',
    'Japan': 'XTKS',
    'Jordan': 'XAMM',
    'Kenya': 'XNAI',
    'Kuwait': 'XKUW',
    'Luxembourg': 'XLUX',
    'Malaysia': 'XKLS',
    'Mexico': 'XMEX',
    'Morocco': 'XCAS',
    'New Zealand': 'XNZE',
    'Nigeria': 'XNSA',
    'Norway': 'XOSL',
    'Norway_NOTC': 'NOTC',
    'Oman': 'XMUS',
    'Pakistan': 'XKAR',
    'Peru': 'XLIM',
    'Philippines': 'XPHS',
    'Poland': 'XWAR',
    'Portugal': 'XLIS',
    'Qatar': 'DSMD',
    'Romania': 'XBSE',
    'Russia': 'MISX',
    'Saudi Arabia': 'XSAU',
    'Senegal': 'XBRV',
    'Singapore': 'XSES',
    'Slovenia': 'XLJU',
    'South Africa': 'XJSE',
    'South Korea': 'XKRX',
    'South Korea_XKOS': 'XKOS',
    'Spain': 'XMAD',
    'Sri Lanka': 'XCOL',
    'Sweden_XNGM': 'XNGM',
    'Sweden': 'XSTO',
    'Switzerland': 'XSWX',
    'Switzerland_XVTX': 'XVTX',
    'Syria': 'XDSE',
    'Taiwan': 'XTAI',
    'Thailand': 'XBKK',
    'The Netherlands_XTOMX': 'TOMX',
    'The Netherlands': 'XAMS',
    'Turkey': 'XIST',
    'United Arab Emirates_XDFM': 'XDFM',
    'United Arab Emirates_DIFX': 'DIFX',
    'United Arab Emirates': 'XADS',
    'United Kingdom_BATE': 'BATE',
    'United Kingdom_CHIX': 'CHIX',
    'United Kingdom': 'XLON',
    'United Kingdom_XPOS': 'XPOS',
    'United Kingdom_TRQX': 'TRQX',
    'United Kingdom_BOAT': 'BOAT',
    'USA_XASE': 'XASE',
    'USA_BATS': 'BATS',
    'USA_XNYS': 'XNYS',
    'USA_ARCX': 'ARCX',
    'USA_XNMS': 'XNMS',
    'USA_XNCM': 'XNCM',
    'USA_OOTC': 'OOTC',
    'USA_XNGS': 'XNGS',
    'USA': '',
    'Vietnam': 'XSTC',
    'Vietnam_HSTC': 'HSTC'
}

currencies = [
    'ALL',
    'AFN',
    'ARS',
    'AWG',
    'AUD',
    'AZN',
    'BSD',
    'BBD',
    'BYN',
    'BZD',
    'BMD',
    'BOB',
    'BAM',
    'BWP',
    'BGN',
    'BRL',
    'BND',
    'KHR',
    'CAD',
    'KYD',
    'CLP',
    'CNY',
    'COP',
    'CRC',
    'HRK',
    'CUP',
    'CZK',
    'DKK',
    'DOP',
    'XCD',
    'EGP',
    'SVC',
    'EUR',
    'FKP',
    'FJD',
    'GHS',
    'GIP',
    'GTQ',
    'GGP',
    'GYD',
    'HNL',
    'HKD',
    'HUF',
    'ISK',
    'INR',
    'IDR',
    'IRR',
    'IMP',
    'ILS',
    'JMD',
    'JPY',
    'JEP',
    'KZT',
    'KPW',
    'KRW',
    'KGS',
    'LAK',
    'LBP',
    'LRD',
    'MKD',
    'MYR',
    'MUR',
    'MXN',
    'MNT',
    'MZN',
    'NAD',
    'NPR',
    'ANG',
    'NZD',
    'NIO',
    'NGN',
    'NOK',
    'OMR',
    'PKR',
    'PAB',
    'PYG',
    'PEN',
    'PHP',
    'PLN',
    'QAR',
    'RON',
    'RUB',
    'SHP',
    'SAR',
    'RSD',
    'SCR',
    'SGD',
    'SBD',
    'SOS',
    'ZAR',
    'LKR',
    'SEK',
    'CHF',
    'SRD',
    'SYP',
    'TWD',
    'THB',
    'TTD',
    'TRY',
    'TVD',
    'UAH',
    'GBP',
    'USD',
    'UYU',
    'UZS',
    'VEF',
    'VND',
    'YER',
    'ZWD'
 ]
